# Generated by Django 5.2.17 on 2026-09-23 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('time_off', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffallocation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_time_off_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_time_off_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='time_off_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='time_off.timeofftype'),
        ),
        migrations.AddField(
            model_name='timeoffallocation',
            name='time_off_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='time_off.timeofftype'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['employee', 'status'], name='timeoff_employee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['start_date', 'end_date'], name='timeoff_date_range_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffallocation',
            index=models.Index(fields=['employee', 'time_off_type'], name='allocation_employee_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeoffallocation',
            constraint=models.UniqueConstraint(fields=('employee', 'time_off_type', 'allocation_year'), name='unique_employee_timeoff_year'),
        ),
    ]
