"""initial peoplepay360 schema

Revision ID: 970747534695
Revises: 
Create Date: 2026-09-05 11:03:50.615494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970747534695'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code'))
    )
    op.create_table('payruns',
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'COMPLETED', 'CANCELLED', name='payrunstatus'), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payruns')),
    sa.UniqueConstraint('period_start', 'period_end', name='uq_payruns_period')
    )
    op.create_table('salary_structures',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_structures')),
    sa.UniqueConstraint('code', name=op.f('uq_salary_structures_code'))
    )
    op.create_table('time_off_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_allocation', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_off_types')),
    sa.UniqueConstraint('code', name=op.f('uq_time_off_types_code'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'HR', 'MANAGER', 'EMPLOYEE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('work_schedules',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('monday_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tuesday_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('wednesday_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('thursday_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('friday_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('saturday_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sunday_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expected_daily_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_schedules'))
    )
    op.create_table('employees',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('employee_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_LEAVE', 'TERMINATED', name='employeestatus'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employees_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('employee_number', name=op.f('uq_employees_employee_number')),
    sa.UniqueConstraint('user_id', name=op.f('uq_employees_user_id'))
    )
    op.create_table('salary_rules',
    sa.Column('salary_structure_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('EARNING', 'DEDUCTION', 'TAX', 'EMPLOYER_CONTRIBUTION', name='salaryrulecategory'), nullable=False),
    sa.Column('calculation_type', sa.Enum('FIXED', 'PERCENTAGE', 'FORMULA', name='calculationtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], name=op.f('fk_salary_rules_salary_structure_id_salary_structures'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_rules')),
    sa.UniqueConstraint('salary_structure_id', 'code', name='uq_salary_rules_structure_code')
    )
    op.create_table('attendance_records',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('work_schedule_id', sa.String(length=36), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('expected_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('worked_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'LATE', 'ON_LEAVE', 'HOLIDAY', name='attendancestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_records_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_schedule_id'], ['work_schedules.id'], name=op.f('fk_attendance_records_work_schedule_id_work_schedules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_attendance_employee_date')
    )
    op.create_table('contracts',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('salary_structure_id', sa.String(length=36), nullable=False),
    sa.Column('work_schedule_id', sa.String(length=36), nullable=True),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('contract_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', name='contracttype'), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'TERMINATED', 'CANCELLED', name='contractstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_contracts_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], name=op.f('fk_contracts_salary_structure_id_salary_structures'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_schedule_id'], ['work_schedules.id'], name=op.f('fk_contracts_work_schedule_id_work_schedules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts')),
    sa.UniqueConstraint('contract_number', name=op.f('uq_contracts_contract_number'))
    )
    op.create_table('time_off_allocations',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('time_off_type_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_time_off_allocations_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['time_off_type_id'], ['time_off_types.id'], name=op.f('fk_time_off_allocations_time_off_type_id_time_off_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_off_allocations')),
    sa.UniqueConstraint('employee_id', 'time_off_type_id', 'year', name='uq_time_off_allocation')
    )
    op.create_table('time_off_requests',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('time_off_type_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('requested_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='timeoffstatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_time_off_requests_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_time_off_requests_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['time_off_type_id'], ['time_off_types.id'], name=op.f('fk_time_off_requests_time_off_type_id_time_off_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_off_requests'))
    )
    op.create_table('payslips',
    sa.Column('payrun_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=True),
    sa.Column('employee_number', sa.String(length=50), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('deductions_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', 'PAID', 'CANCELLED', name='payslipstatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_payslips_contract_id_contracts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payslips_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], name=op.f('fk_payslips_payrun_id_payruns'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payslips'))
    )
    op.create_table('payslip_lines',
    sa.Column('payslip_id', sa.String(length=36), nullable=False),
    sa.Column('salary_rule_id', sa.String(length=36), nullable=True),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], name=op.f('fk_payslip_lines_payslip_id_payslips'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_rule_id'], ['salary_rules.id'], name=op.f('fk_payslip_lines_salary_rule_id_salary_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payslip_lines'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payslip_lines')
    op.drop_table('payslips')
    op.drop_table('time_off_requests')
    op.drop_table('time_off_allocations')
    op.drop_table('contracts')
    op.drop_table('attendance_records')
    op.drop_table('salary_rules')
    op.drop_table('employees')
    op.drop_table('work_schedules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('time_off_types')
    op.drop_table('salary_structures')
    op.drop_table('payruns')
    op.drop_table('departments')
    # ### end Alembic commands ###
