# Generated by Django 5.2.17 on 2026-09-23 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPUTED', 'Computed'), ('VALIDATED', 'Validated'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('deduction_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_employees', models.ManyToManyField(blank=True, related_name='selected_payruns', to='employees.employee')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payruns', to='payroll.salarystructure')),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('employee_number_snapshot', models.CharField(max_length=50)),
                ('employee_name_snapshot', models.CharField(max_length=200)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='contracts.contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee')),
                ('payrun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrun')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.salarystructure')),
            ],
            options={
                'ordering': ['-period_start', 'employee_number_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('BASIC', 'Basic'), ('ALLOWANCE', 'Allowance'), ('GROSS', 'Gross'), ('DEDUCTION', 'Deduction'), ('NET', 'Net')], max_length=20)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage'), ('FORMULA', 'Formula')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('formula', models.TextField(blank=True)),
                ('based_on', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='payroll.salarystructure')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=20)),
                ('sequence', models.PositiveIntegerField()),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
                ('salary_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='payroll.salaryrule')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['payslip', 'sequence'], name='payslip_line_sequence_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='salaryrule',
            index=models.Index(fields=['salary_structure', 'sequence'], name='salary_rule_sequence_idx'),
        ),
        migrations.AddConstraint(
            model_name='salaryrule',
            constraint=models.UniqueConstraint(fields=('salary_structure', 'code'), name='unique_salary_rule_code'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', 'period_start'], name='payslip_employee_period_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['status'], name='payslip_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('payrun', 'employee'), name='unique_employee_payslip_per_payrun'),
        ),
        migrations.AddIndex(
            model_name='payrun',
            index=models.Index(fields=['period_start', 'period_end'], name='payrun_period_idx'),
        ),
        migrations.AddIndex(
            model_name='payrun',
            index=models.Index(fields=['status'], name='payrun_status_idx'),
        ),
    ]
