# Generated by Django 5.2.17 on 2026-09-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='worked_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
